# Placer ce fichier dans un contexte plus haut, donc à côté du dossier customerManager et du site web.

version: '2.4'
services:
    webapp:
        image: httpd:2.4-apache
        build:
            context: carlmelanie-masso-webApp/webapp/
            dockerfile: Dockerfile
        environment:
          - API_URL=test #'http://localhost:63212/api/'
        networks:
        - local
        ports:
        - '80:80'
        - '443:443'
        volumes:
        - type: bind
          source: ./carlmelanie-masso-webApp/webapp/src
          target: /var/www/html
    webapi:
        image: alpine:3.9
        build:
            context: customerManager/WebApi/WebApi/
            dockerfile: WebApi/Dockerfile
        networks:
        - local
        ports:
        - '8080:80'
    database:
        container_name: database
        image: mysql:8
        build:
            context: customerManager/database/
            dockerfile: Dockerfile
        environment:
        - MYSQL_ROOT_PASSWORD=admin
        networks:
        - local
        ports:
        - '3306:3306'
networks:
    local:
        name: local_network
