version: 3.1

services:
    mysql:
        image: mysql:latest
        build:
            context: mysql
            dockerfile: Dockerfile
        restart: always
        env:
            - MYSQL_ROOT_PASSWORD: DummyPassword

volumes:

